class_name DocIndexGenerator
extends RefCounted

func render(validation_result: Dictionary) -> String:
	var lines: Array[String] = [
		"<!-- GENERATED BY res://tools/docs/generate_index.gd; DO NOT EDIT -->",
		"# Requirement Index", "",
		"| requirement_id | packet_id | path | specification_status | beads |",
		"|---|---|---|---|---|",
	]
	var requirements: Array = validation_result.get("requirements", []).duplicate(true)
	requirements.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return str(a.id) < str(b.id))
	var packets_by_id := {}
	for packet: Dictionary in validation_result.get("packets", []): packets_by_id[packet.id] = packet
	for requirement: Dictionary in requirements:
		var packet: Dictionary = packets_by_id[requirement.packet_id]
		var beads: Array = packet.get("beads", []).duplicate(); beads.sort()
		lines.append("| `%s` | `%s` | `%s` | `%s` | `%s` |" % [requirement.id, requirement.packet_id, requirement.path, requirement.specification_status, ",".join(beads)])
	lines.append("")
	lines.append("blocked_requirement_ids: " + JSON.stringify(validation_result.get("blocked_requirement_ids", [])))
	return "\n".join(lines) + "\n"

func write_index(path: String, content: String) -> Error:
	var directory_error := DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(path.get_base_dir()))
	if directory_error not in [OK, ERR_ALREADY_EXISTS]: return directory_error
	var temporary := "%s.%s.tmp" % [path, str(Time.get_unix_time_from_system()).replace(".", "-") + "-" + str(randi())]
	var file := FileAccess.open(temporary, FileAccess.WRITE)
	if file == null: return FileAccess.get_open_error()
	file.store_buffer(content.to_utf8_buffer())
	file.flush()
	file.close()
	var temporary_absolute := ProjectSettings.globalize_path(temporary)
	var target_absolute := ProjectSettings.globalize_path(path)
	# One same-directory replace is the commit point. Never delete or rename the old target first.
	# Godot's Windows backend uses replace-existing rename semantics; on a backend that refuses
	# replacement, this returns an error and the old target remains byte-for-byte intact.
	var promote_error := DirAccess.rename_absolute(temporary_absolute, target_absolute)
	if promote_error != OK and FileAccess.file_exists(temporary):
		var cleanup_error := DirAccess.remove_absolute(temporary_absolute)
		if cleanup_error != OK: return cleanup_error
	return promote_error
