from pathlib import Path
import hashlib,json,re,subprocess,xml.etree.ElementTree as ET
ROOT=Path('/workspace/scratch/e169b180163f'); REPO=ROOT/'dwm'; OLD=ROOT/'historical-objects'; OUT=ROOT/'settings-window-source-review'; OUT.mkdir(exist_ok=True); (OUT/'upstream').mkdir(exist_ok=True)
BASE='5a581fc89121864aead5202e01d6a82423b1b52d';SOURCE='63b59b67a169a34a17f0f5ec4c15b98a55c6ff2b'; GODOT='35e80b3a8822a9df9be390814b62f44c0a9c69e8'
def ident(raw):return {'bytes':len(raw),'sha256':hashlib.sha256(raw).hexdigest(),'git_blob':hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()}
def git(*args):return subprocess.check_output(['git','-C',str(REPO),*args])
def blob(commit,path):return git('show',commit+':'+path)
metadata=json.loads((OLD/'godot-main-blob-metadata.json').read_text())+json.loads((OLD/'godot-gui-blob-metadata.json').read_text());upstream=[]
for m in metadata:
 retained=OLD/('godot-'+m['name']);data=retained.read_bytes()
 # The original Add File transport appended one blank final line. Never infer
 # content normalization: the exact one-byte removal must reproduce API blob ID.
 raw=data if ident(data)['git_blob']==m['sha'] else data[:-1]
 assert data==raw or data==raw+b'\n'
 assert ident(raw)['git_blob']==m['sha'] and len(raw)==m['size']
 target=OUT/'upstream'/m['name'];target.write_bytes(raw)
 upstream.append({'path':m['path'],'commit':GODOT,'url':f'https://github.com/godotengine/godot/blob/{GODOT}/{m["path"]}','raw_url':f'https://raw.githubusercontent.com/godotengine/godot/{GODOT}/{m["path"]}','upstream_git_blob':m['sha'],'api_blob_identity_verified':True,'retained_path':str(retained),'retained_identity':ident(data),'exact_copy':str(target.relative_to(OUT)),'exact_identity':ident(raw),'transport_extra_terminal_newline_removed':data!=raw})
production=['scripts/ui/pause/PauseQuickCommands.gd','scripts/ui/pause/PauseSurface.gd']
changed=git('diff','--name-only',BASE,SOURCE,'--','scripts','autoload').decode().splitlines();assert changed==production
identities=[]
for p in production:identities.append({'path':p,'before':ident(blob(BASE,p)),'after':ident(blob(SOURCE,p))})
diff=git('diff','--binary','--no-renames',BASE,SOURCE,'--',*production);(OUT/'production.diff').write_bytes(diff)
testpath='tests/unit/test_production_pause_controller.gd';before=blob(BASE,testpath);after=blob(SOURCE,testpath)
names=lambda raw:set(re.findall(r'^func (test_\w+)\s*\(',raw.decode(),re.M))
added=sorted(names(after)-names(before));removed=sorted(names(before)-names(after));assert len(added)==6 and not removed
expected={'test_paused_settings_quick_save_keeps_host_focus_and_exact_canonical_source','test_paused_settings_quick_load_remains_unavailable_and_cannot_wake_on_exit','test_paused_settings_reset_window_forwards_contacts_without_saving_or_queued_replay','test_paused_settings_option_popup_forwards_release_and_retires_same_frame_save','test_paused_settings_binding_capture_never_saves_and_requires_fresh_release','test_paused_settings_pending_preference_commit_retires_save_until_release'};assert set(added)==expected
original='test_paused_quick_refusal_is_visible_and_settings_custody_blocks_shortcuts';assert original in names(before)&names(after)
focus=ROOT/'settings-focus1';xml=focus/'artifacts/windows-reading_delivery-36964699167-1/ci/reading_delivery.xml';xt=ET.parse(xml).getroot();assert xt.get('tests')=='388'and xt.get('failures')=='1'
failed=[{'script':s.get('name'),'case':c.get('name')} for s in xt.findall('testsuite')for c in s.findall('testcase')if c.get('status')!='pass'];assert len(failed)==1 and failed[0]['case']=='test_paused_settings_reset_window_forwards_contacts_without_saving_or_queued_replay'
log=focus/'logs/110706676237.log';assert log.exists();assert 'e6d445343c292342310359faa898aabd2959f4db' in log.read_text()
run=json.loads((focus/'run.json').read_text());assert run['id']==36964699167 and run['conclusion']=='failure'
report={'schema_version':1,'scope':'Source analysis and retained failed-test diagnosis only; no current cloud acceptance claim.','reviewed_source':SOURCE,'baseline':BASE,'focus2_run_id':36965784091,'focus2_acceptance_claimed':False,'engines_executed_locally':False,'godot':{'tag':'4.6.3-stable','resolved_commit':GODOT,'ref_metadata':ident((OLD/'godot-463-ref.json').read_bytes()),'sources':upstream},'findings':[
 {'id':'native_popup_contacts','basis':['scene/main/viewport.cpp:3464','scene/main/viewport.cpp:3501','scene/main/window.cpp:1879','scene/gui/option_button.cpp:651'],'conclusion':'Embedded subwindow dispatch returns before parent _input. OptionButton owns an internal PopupMenu. A contact pressed in Settings and released in that popup bypassed the shared parent ledger; popup-only presses were also absent. Visibility snapshots alone cannot observe packets that never reached the ledger.','classification':'Production input-custody gap inferred from exact engine and project source; cloud regression required.'},
 {'id':'reset_dispatch_fixture','basis':['scene/main/window.cpp:1897','scene/gui/dialogs.cpp:39','scene/gui/dialogs.cpp:144'],'conclusion':'Direct Window.push_input bypasses Window::_input_from_window, where AcceptDialog recognizes native Escape. Cancel schedules hide deferred. The original test therefore never canceled its native dialog; later Quick assertions failed behind that still-open owner. The revised test enters through the embedded parent viewport and resumes at the real hide signal before the immediate held-contact retry.','classification':'Focus1 observed test failure, explained by exact engine dispatch.'},
 {'id':'single_owner_fix','basis':['scripts/ui/pause/PauseQuickCommands.gd:11','scripts/ui/pause/PauseQuickCommands.gd:71','scripts/ui/pause/PauseSurface.gd:307'],'conclusion':'Each mounted Settings Window gets a private ALWAYS input observer forwarding to the existing InputManager and immediately retaining those contacts. No visibility guard drops final packets after native hiding; visibility signals also retire contacts synchronously. No second contact ledger, Save owner, or durable format is introduced. Settings F5 admission remains action-specific; F9 is outside this bounded admission.'}
 ],'production_changes':identities,'production_diff':{'path':'production.diff',**ident(diff)},'only_two_production_files_changed':True,'reset_seam_reverted_to_baseline':{p:blob(BASE,p)==blob(SOURCE,p)for p in ['scripts/ui/SettingsContent.gd','scripts/ui/SettingsResetConfirmation.gd']},'gut_cases':{'script':testpath,'before':ident(before),'after':ident(after),'added':added,'removed':removed,'historical_identity_preserved':original,'expected_broad_counts':{'case_executions':2286,'unique_cases':2282,'unique_scripts':194,'script_executions':195,'xml_count':13}},'focus1_failure':{'run_id':run['id'],'workflow_head':run['head_sha'],'source':'e6d445343c292342310359faa898aabd2959f4db','job_id':110706676237,'tests':388,'passed':387,'failed_cases':failed,'failed_assertion_source_lines':[1077,1084,1094,1095],'xml':{'path':str(xml.relative_to(ROOT)),**ident(xml.read_bytes())},'job_log':{'path':str(log.relative_to(ROOT)),**ident(log.read_bytes())},'limits':'The separate Focus1 rendered settings-read failure is not diagnosed by this source review.'},'independent_review':{'reviewer':'/root/historical_objects/settings_f5_review','status':'No further static blockers identified after shared Window observer and embedded dispatch repair.','verified_boundaries':['Existing InputManager is the sole contact ledger.','Window observers retire packets synchronously, including packets after native hide.','Mounted-tree traversal includes internal OptionButton popups and terminates after its observer nodes.','Settings F9 exclusion and canonical Save ownership remain intact.'],'limitation':'Read-only review; not engine execution or broad acceptance.'}}
(OUT/'source-review.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps({'receipt':str(OUT/'source-review.json'),'source':SOURCE,'production_files':2,'new_cases':len(added),'verified_upstream_blobs':len(upstream),'cloud_acceptance':False}))
