extends RefCounted
## Authored accessibility tuples. See docs/design/current-ui/minesweeper-presentation-tuples.md.
## Exact Day 1 tables; the installed day ages room materials only, never semantic state colours.

const WEEK_TINT := preload("res://scripts/ui/theme/WeekTint.gd")

const TUPLES := {
	"after_hours/standard/standard": {
		&"habitat": Color("0b0d13"), &"controlled_face": Color("151b25"),
		&"paper": Color("c3baa3"), &"primary_paper_copy": Color("151b25"),
		&"secondary_paper_copy": Color("2f2936"), &"primary_dark_copy": Color("d8cfb7"),
		&"secondary_dark_copy": Color("9ea8a2"), &"dark_registration": Color("657d89"),
		&"dark_scroll_thumb": Color("d8cfb7"), &"paper_scroll_thumb": Color("644000"),
		&"dark_mark": Color("d8cfb7"), &"paper_mark": Color("151b25"),
		&"selected_plane": Color("789083"), &"selected_ink": Color("151b25"),
		&"paper_structure": Color("151b25"), &"dark_separation": Color("0b0d13"),
		&"dark_focus_outer": Color("d8cfb7"), &"dark_focus_inner": Color("a9935f"),
		&"paper_focus_outer": Color("0b0d13"), &"paper_focus_inner": Color("644000"),
		&"filed_focus_outer": Color("0b0d13"), &"filed_focus_inner": Color("151b25"),
		&"technical_error": Color("dd7a7f"),
	},
	"after_hours/standard/protan": {
		&"habitat": Color("0b0d13"), &"controlled_face": Color("151b25"),
		&"paper": Color("c3baa3"), &"primary_paper_copy": Color("151b25"),
		&"secondary_paper_copy": Color("2f2936"), &"primary_dark_copy": Color("d8cfb7"),
		&"secondary_dark_copy": Color("9ea8a2"), &"dark_registration": Color("657d89"),
		&"dark_scroll_thumb": Color("d8cfb7"), &"paper_scroll_thumb": Color("5d3d00"),
		&"dark_mark": Color("d8cfb7"), &"paper_mark": Color("151b25"),
		&"selected_plane": Color("7d94ae"), &"selected_ink": Color("151b25"),
		&"paper_structure": Color("151b25"), &"dark_separation": Color("0b0d13"),
		&"dark_focus_outer": Color("d8cfb7"), &"dark_focus_inner": Color("c0a06a"),
		&"paper_focus_outer": Color("0b0d13"), &"paper_focus_inner": Color("5d3d00"),
		&"filed_focus_outer": Color("0b0d13"), &"filed_focus_inner": Color("151b25"),
		&"technical_error": Color("b8a4d8"),
	},
	"after_hours/standard/deutan": {
		&"habitat": Color("0b0d13"), &"controlled_face": Color("151b25"),
		&"paper": Color("c3baa3"), &"primary_paper_copy": Color("151b25"),
		&"secondary_paper_copy": Color("2f2936"), &"primary_dark_copy": Color("d8cfb7"),
		&"secondary_dark_copy": Color("9ea8a2"), &"dark_registration": Color("657d89"),
		&"dark_scroll_thumb": Color("d8cfb7"), &"paper_scroll_thumb": Color("4f3d00"),
		&"dark_mark": Color("d8cfb7"), &"paper_mark": Color("151b25"),
		&"selected_plane": Color("869aaa"), &"selected_ink": Color("151b25"),
		&"paper_structure": Color("151b25"), &"dark_separation": Color("0b0d13"),
		&"dark_focus_outer": Color("d8cfb7"), &"dark_focus_inner": Color("bea86a"),
		&"paper_focus_outer": Color("0b0d13"), &"paper_focus_inner": Color("4f3d00"),
		&"filed_focus_outer": Color("0b0d13"), &"filed_focus_inner": Color("151b25"),
		&"technical_error": Color("c1a5c5"),
	},
	"after_hours/standard/tritan": {
		&"habitat": Color("0b0d13"), &"controlled_face": Color("151b25"),
		&"paper": Color("c3baa3"), &"primary_paper_copy": Color("151b25"),
		&"secondary_paper_copy": Color("2f2936"), &"primary_dark_copy": Color("d8cfb7"),
		&"secondary_dark_copy": Color("9ea8a2"), &"dark_registration": Color("657d89"),
		&"dark_scroll_thumb": Color("d8cfb7"), &"paper_scroll_thumb": Color("653936"),
		&"dark_mark": Color("d8cfb7"), &"paper_mark": Color("151b25"),
		&"selected_plane": Color("a59289"), &"selected_ink": Color("151b25"),
		&"paper_structure": Color("151b25"), &"dark_separation": Color("0b0d13"),
		&"dark_focus_outer": Color("d8cfb7"), &"dark_focus_inner": Color("d0a099"),
		&"paper_focus_outer": Color("0b0d13"), &"paper_focus_inner": Color("653936"),
		&"filed_focus_outer": Color("0b0d13"), &"filed_focus_inner": Color("151b25"),
		&"technical_error": Color("c7a5b9"),
	},
	"after_hours/high/standard": {
		&"habitat": Color("080b10"), &"controlled_face": Color("0b1018"),
		&"paper": Color("e9e2d0"), &"primary_paper_copy": Color("0b1018"),
		&"secondary_paper_copy": Color("24212d"), &"primary_dark_copy": Color("f6efdc"),
		&"secondary_dark_copy": Color("c1c9c1"), &"dark_registration": Color("98a7ae"),
		&"dark_scroll_thumb": Color("f6efdc"), &"paper_scroll_thumb": Color("5b3900"),
		&"dark_mark": Color("f6efdc"), &"paper_mark": Color("0b1018"),
		&"selected_plane": Color("9fab9f"), &"selected_ink": Color("0b1018"),
		&"paper_structure": Color("0b1018"), &"dark_separation": Color("080b10"),
		&"dark_focus_outer": Color("f6efdc"), &"dark_focus_inner": Color("d0b977"),
		&"paper_focus_outer": Color("080b10"), &"paper_focus_inner": Color("5b3900"),
		&"filed_focus_outer": Color("080b10"), &"filed_focus_inner": Color("0b1018"),
		&"technical_error": Color("f2a5ad"),
	},
	"after_hours/high/protan": {
		&"habitat": Color("080b10"), &"controlled_face": Color("0b1018"),
		&"paper": Color("e9e2d0"), &"primary_paper_copy": Color("0b1018"),
		&"secondary_paper_copy": Color("24212d"), &"primary_dark_copy": Color("f6efdc"),
		&"secondary_dark_copy": Color("c1c9c1"), &"dark_registration": Color("98a7ae"),
		&"dark_scroll_thumb": Color("f6efdc"), &"paper_scroll_thumb": Color("503500"),
		&"dark_mark": Color("f6efdc"), &"paper_mark": Color("0b1018"),
		&"selected_plane": Color("a7b7cd"), &"selected_ink": Color("0b1018"),
		&"paper_structure": Color("0b1018"), &"dark_separation": Color("080b10"),
		&"dark_focus_outer": Color("f6efdc"), &"dark_focus_inner": Color("e0c187"),
		&"paper_focus_outer": Color("080b10"), &"paper_focus_inner": Color("503500"),
		&"filed_focus_outer": Color("080b10"), &"filed_focus_inner": Color("0b1018"),
		&"technical_error": Color("d3bceb"),
	},
	"after_hours/high/deutan": {
		&"habitat": Color("080b10"), &"controlled_face": Color("0b1018"),
		&"paper": Color("e9e2d0"), &"primary_paper_copy": Color("0b1018"),
		&"secondary_paper_copy": Color("24212d"), &"primary_dark_copy": Color("f6efdc"),
		&"secondary_dark_copy": Color("c1c9c1"), &"dark_registration": Color("98a7ae"),
		&"dark_scroll_thumb": Color("f6efdc"), &"paper_scroll_thumb": Color("4f3d00"),
		&"dark_mark": Color("f6efdc"), &"paper_mark": Color("0b1018"),
		&"selected_plane": Color("acbecd"), &"selected_ink": Color("0b1018"),
		&"paper_structure": Color("0b1018"), &"dark_separation": Color("080b10"),
		&"dark_focus_outer": Color("f6efdc"), &"dark_focus_inner": Color("d9c585"),
		&"paper_focus_outer": Color("080b10"), &"paper_focus_inner": Color("4f3d00"),
		&"filed_focus_outer": Color("080b10"), &"filed_focus_inner": Color("0b1018"),
		&"technical_error": Color("ddc1df"),
	},
	"after_hours/high/tritan": {
		&"habitat": Color("080b10"), &"controlled_face": Color("0b1018"),
		&"paper": Color("e9e2d0"), &"primary_paper_copy": Color("0b1018"),
		&"secondary_paper_copy": Color("24212d"), &"primary_dark_copy": Color("f6efdc"),
		&"secondary_dark_copy": Color("c1c9c1"), &"dark_registration": Color("98a7ae"),
		&"dark_scroll_thumb": Color("f6efdc"), &"paper_scroll_thumb": Color("5b302e"),
		&"dark_mark": Color("f6efdc"), &"paper_mark": Color("0b1018"),
		&"selected_plane": Color("c4aba2"), &"selected_ink": Color("0b1018"),
		&"paper_structure": Color("0b1018"), &"dark_separation": Color("080b10"),
		&"dark_focus_outer": Color("f6efdc"), &"dark_focus_inner": Color("e3b6ac"),
		&"paper_focus_outer": Color("080b10"), &"paper_focus_inner": Color("5b302e"),
		&"filed_focus_outer": Color("080b10"), &"filed_focus_inner": Color("0b1018"),
		&"technical_error": Color("dfc0d1"),
	},
	"midnight/standard/standard": {
		&"habitat": Color("0d1514"), &"controlled_face": Color("14201d"),
		&"paper": Color("c3baa3"), &"primary_paper_copy": Color("14201d"),
		&"secondary_paper_copy": Color("2f2936"), &"primary_dark_copy": Color("d8cfb7"),
		&"secondary_dark_copy": Color("9ea8a2"), &"dark_registration": Color("657d89"),
		&"dark_scroll_thumb": Color("d8cfb7"), &"paper_scroll_thumb": Color("644000"),
		&"dark_mark": Color("d8cfb7"), &"paper_mark": Color("14201d"),
		&"selected_plane": Color("789083"), &"selected_ink": Color("14201d"),
		&"paper_structure": Color("14201d"), &"dark_separation": Color("0d1514"),
		&"dark_focus_outer": Color("d8cfb7"), &"dark_focus_inner": Color("a9935f"),
		&"paper_focus_outer": Color("0d1514"), &"paper_focus_inner": Color("644000"),
		&"filed_focus_outer": Color("0d1514"), &"filed_focus_inner": Color("14201d"),
		&"technical_error": Color("dd7a7f"),
	},
	"midnight/standard/protan": {
		&"habitat": Color("0d1514"), &"controlled_face": Color("14201d"),
		&"paper": Color("c3baa3"), &"primary_paper_copy": Color("14201d"),
		&"secondary_paper_copy": Color("2f2936"), &"primary_dark_copy": Color("d8cfb7"),
		&"secondary_dark_copy": Color("9ea8a2"), &"dark_registration": Color("657d89"),
		&"dark_scroll_thumb": Color("d8cfb7"), &"paper_scroll_thumb": Color("5d3d00"),
		&"dark_mark": Color("d8cfb7"), &"paper_mark": Color("14201d"),
		&"selected_plane": Color("7d94ae"), &"selected_ink": Color("14201d"),
		&"paper_structure": Color("14201d"), &"dark_separation": Color("0d1514"),
		&"dark_focus_outer": Color("d8cfb7"), &"dark_focus_inner": Color("c0a06a"),
		&"paper_focus_outer": Color("0d1514"), &"paper_focus_inner": Color("5d3d00"),
		&"filed_focus_outer": Color("0d1514"), &"filed_focus_inner": Color("14201d"),
		&"technical_error": Color("b8a4d8"),
	},
	"midnight/standard/deutan": {
		&"habitat": Color("0d1514"), &"controlled_face": Color("14201d"),
		&"paper": Color("c3baa3"), &"primary_paper_copy": Color("14201d"),
		&"secondary_paper_copy": Color("2f2936"), &"primary_dark_copy": Color("d8cfb7"),
		&"secondary_dark_copy": Color("9ea8a2"), &"dark_registration": Color("657d89"),
		&"dark_scroll_thumb": Color("d8cfb7"), &"paper_scroll_thumb": Color("4f3d00"),
		&"dark_mark": Color("d8cfb7"), &"paper_mark": Color("14201d"),
		&"selected_plane": Color("869aaa"), &"selected_ink": Color("14201d"),
		&"paper_structure": Color("14201d"), &"dark_separation": Color("0d1514"),
		&"dark_focus_outer": Color("d8cfb7"), &"dark_focus_inner": Color("bea86a"),
		&"paper_focus_outer": Color("0d1514"), &"paper_focus_inner": Color("4f3d00"),
		&"filed_focus_outer": Color("0d1514"), &"filed_focus_inner": Color("14201d"),
		&"technical_error": Color("c1a5c5"),
	},
	"midnight/standard/tritan": {
		&"habitat": Color("0d1514"), &"controlled_face": Color("14201d"),
		&"paper": Color("c3baa3"), &"primary_paper_copy": Color("14201d"),
		&"secondary_paper_copy": Color("2f2936"), &"primary_dark_copy": Color("d8cfb7"),
		&"secondary_dark_copy": Color("9ea8a2"), &"dark_registration": Color("657d89"),
		&"dark_scroll_thumb": Color("d8cfb7"), &"paper_scroll_thumb": Color("653936"),
		&"dark_mark": Color("d8cfb7"), &"paper_mark": Color("14201d"),
		&"selected_plane": Color("a59289"), &"selected_ink": Color("14201d"),
		&"paper_structure": Color("14201d"), &"dark_separation": Color("0d1514"),
		&"dark_focus_outer": Color("d8cfb7"), &"dark_focus_inner": Color("d0a099"),
		&"paper_focus_outer": Color("0d1514"), &"paper_focus_inner": Color("653936"),
		&"filed_focus_outer": Color("0d1514"), &"filed_focus_inner": Color("14201d"),
		&"technical_error": Color("c7a5b9"),
	},
	"midnight/high/standard": {
		&"habitat": Color("07100c"), &"controlled_face": Color("0c1811"),
		&"paper": Color("e9e2d0"), &"primary_paper_copy": Color("0c1811"),
		&"secondary_paper_copy": Color("24212d"), &"primary_dark_copy": Color("f6efdc"),
		&"secondary_dark_copy": Color("c1c9c1"), &"dark_registration": Color("98a7ae"),
		&"dark_scroll_thumb": Color("f6efdc"), &"paper_scroll_thumb": Color("5b3900"),
		&"dark_mark": Color("f6efdc"), &"paper_mark": Color("0c1811"),
		&"selected_plane": Color("9fab9f"), &"selected_ink": Color("0c1811"),
		&"paper_structure": Color("0c1811"), &"dark_separation": Color("07100c"),
		&"dark_focus_outer": Color("f6efdc"), &"dark_focus_inner": Color("d0b977"),
		&"paper_focus_outer": Color("07100c"), &"paper_focus_inner": Color("5b3900"),
		&"filed_focus_outer": Color("07100c"), &"filed_focus_inner": Color("0c1811"),
		&"technical_error": Color("f2a5ad"),
	},
	"midnight/high/protan": {
		&"habitat": Color("07100c"), &"controlled_face": Color("0c1811"),
		&"paper": Color("e9e2d0"), &"primary_paper_copy": Color("0c1811"),
		&"secondary_paper_copy": Color("24212d"), &"primary_dark_copy": Color("f6efdc"),
		&"secondary_dark_copy": Color("c1c9c1"), &"dark_registration": Color("98a7ae"),
		&"dark_scroll_thumb": Color("f6efdc"), &"paper_scroll_thumb": Color("503500"),
		&"dark_mark": Color("f6efdc"), &"paper_mark": Color("0c1811"),
		&"selected_plane": Color("a7b7cd"), &"selected_ink": Color("0c1811"),
		&"paper_structure": Color("0c1811"), &"dark_separation": Color("07100c"),
		&"dark_focus_outer": Color("f6efdc"), &"dark_focus_inner": Color("e0c187"),
		&"paper_focus_outer": Color("07100c"), &"paper_focus_inner": Color("503500"),
		&"filed_focus_outer": Color("07100c"), &"filed_focus_inner": Color("0c1811"),
		&"technical_error": Color("d3bceb"),
	},
	"midnight/high/deutan": {
		&"habitat": Color("07100c"), &"controlled_face": Color("0c1811"),
		&"paper": Color("e9e2d0"), &"primary_paper_copy": Color("0c1811"),
		&"secondary_paper_copy": Color("24212d"), &"primary_dark_copy": Color("f6efdc"),
		&"secondary_dark_copy": Color("c1c9c1"), &"dark_registration": Color("98a7ae"),
		&"dark_scroll_thumb": Color("f6efdc"), &"paper_scroll_thumb": Color("4f3d00"),
		&"dark_mark": Color("f6efdc"), &"paper_mark": Color("0c1811"),
		&"selected_plane": Color("acbecd"), &"selected_ink": Color("0c1811"),
		&"paper_structure": Color("0c1811"), &"dark_separation": Color("07100c"),
		&"dark_focus_outer": Color("f6efdc"), &"dark_focus_inner": Color("d9c585"),
		&"paper_focus_outer": Color("07100c"), &"paper_focus_inner": Color("4f3d00"),
		&"filed_focus_outer": Color("07100c"), &"filed_focus_inner": Color("0c1811"),
		&"technical_error": Color("ddc1df"),
	},
	"midnight/high/tritan": {
		&"habitat": Color("07100c"), &"controlled_face": Color("0c1811"),
		&"paper": Color("e9e2d0"), &"primary_paper_copy": Color("0c1811"),
		&"secondary_paper_copy": Color("24212d"), &"primary_dark_copy": Color("f6efdc"),
		&"secondary_dark_copy": Color("c1c9c1"), &"dark_registration": Color("98a7ae"),
		&"dark_scroll_thumb": Color("f6efdc"), &"paper_scroll_thumb": Color("5b302e"),
		&"dark_mark": Color("f6efdc"), &"paper_mark": Color("0c1811"),
		&"selected_plane": Color("c4aba2"), &"selected_ink": Color("0c1811"),
		&"paper_structure": Color("0c1811"), &"dark_separation": Color("07100c"),
		&"dark_focus_outer": Color("f6efdc"), &"dark_focus_inner": Color("e3b6ac"),
		&"paper_focus_outer": Color("07100c"), &"paper_focus_inner": Color("5b302e"),
		&"filed_focus_outer": Color("07100c"), &"filed_focus_inner": Color("0c1811"),
		&"technical_error": Color("dfc0d1"),
	},
}


static func resolve(palette: StringName, high_contrast: bool, colour_preset: String) -> Dictionary:
	var contrast := "high" if high_contrast else "standard"
	var key := "%s/%s/%s" % [String(palette), contrast, colour_preset]
	if not TUPLES.has(key):
		return {}
	return TUPLES[key].duplicate()


## The shared week curve changes room materials at scene/day boundaries. Marks,
## focus, mine numbers and selected/error colours retain their authored tuples.
static func resolve_tinted(palette: StringName, high_contrast: bool, colour_preset: String, day: int) -> Dictionary:
	var roles := resolve(palette, high_contrast, colour_preset)
	if roles.is_empty() or day not in range(1, 8): return {}
	var room := WEEK_TINT.apply({
		"habitat": roles[&"habitat"], "face": roles[&"controlled_face"],
		"paper": roles[&"paper"], "structure": roles[&"paper_structure"],
	}, WEEK_TINT.tint_for_day(day), high_contrast, colour_preset)
	roles[&"habitat"] = room.habitat
	roles[&"controlled_face"] = room.face
	roles[&"paper"] = room.paper
	roles[&"paper_structure"] = room.structure
	roles[&"dark_separation"] = room.habitat
	return roles
